"version": 3
services:
  nginx:
    image: nginx:stable
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web/logs/nginx/:/var/log/nginx
      - ./web:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
